apiVersion: apps/v1
kind: Deployment
metadata:
  name: studyblocks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studyblocks
  template:
    metadata:
      labels:
        app: studyblocks
    spec:
      containers:
      - name: studyblocks
        image: abhii2310/studyblocks:latest
        ports:
        - containerPort: 80
