name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Using v4 for the latest features and security

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Using v4
      with:
        node-version: '18.x'
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: CI=false npm run build
