name: Postman API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  postman-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install backend dependencies
        run: |
          cd server
          npm ci

      - name: Start backend server
        run: |
          cd server
          npm run start &
          sleep 10

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman API tests
        run: |
          newman run StudyBlocks-Postman-Collection.json --env-var base_url=http://localhost:4000
        working-directory: .

      - name: Archive Newman reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: postman-reports
          path: newman/*
